name: Automated Builds

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'appveyor.yml'
      - 'scripts/*'
      - '.github/ISSUE_TEMPLATE/*'
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '**.md'
      - 'appveyor.yml'
      - 'scripts/*'
      - '.github/ISSUE_TEMPLATE/*'

jobs:
  windows:
    name: 💻 Windows
    uses: "./.github/workflows/windows-build.yml"
